### ISSUE TITLE
Document use cases?

### ISSUE THREAD

**Issue by fullofcaffeine** [PhilDL/epic-stack-monorepo#6]
Hi!

Thanks for creating and sharing this! This looks quite interesting! I found it while searching for an epic-web boilerplate that used `ppm` instead of `npm.` 

It's not clear what the goals behind the monorepo are, though. Is the (main) use case to have multiple (different) apps in the same repo while sharing common bits and libraries between them? Why would someone use this instead of a regular `epic-stack` boilerplate? I think it'd be worth clarifying it in the README (e.g what are the production advantages? Why would someone use this in production instead of a regular boilerplate? Pros/Cons etc).

Thanks!

**Comment by PhilDL** [comment]
Hello,

I could try to write an introduction to why but this is basically asking what are the advantage of a Monorepo which I think is already answered online by various people more articulate than me. But I could write something in the README, yes.

To answer you quickly, without formatting my thoughts:



- A monorepo on a big-scale project could reflect your organization, do you have a backend-team owning a part of the app, an UI/UX team that should be able to work on their own repo? A monorepo could reflect the actual organization of the company.
- As an agency or a solo developper you could use a monorepo to extract some reusable modules, you did a great GoogleCalendar Remix integration, or a stripe integration ? Put these as `packages` and use them in your different `apps`.
- Generally, thinking in module forces you to think a lot about the dependencies you are embarking. In the end sometimes pushing you to use ports and adapters patterns, create a more generic code that doesn't have a concrete implementation. You tend to think about a business domain, and don't implement concrete Database queries for example. One remix app could use Prisma and another one Drizzle, with different DB but your core domain knowledge stays in its own package...

That's what I think on the top of my head for now... Will come back to it later.

**Comment by PhilDL** [comment]
This repo is not used anymore as an example for the epic-stack.
